import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Recipes</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <Main>
        <MainHeader> My Recipes</MainHeader>
        <p> </p>
      </Main>
    </div>
  );
}

const Main = styled.main`
  text-align: center;
`;

const MainHeader = styled.h1`
  background-color: white;
  color: green;
`;
